"""sdi init — initialize SDI in a git repository."""

from __future__ import annotations

import sys
from pathlib import Path

import click

from sdi.snapshot.storage import write_atomic

_CONFIG_TEMPLATE = """\
# SDI Configuration — generated by `sdi init`
# Uncomment and modify values to override defaults.
# Full documentation: https://github.com/GeoffGodwin/sdi

[core]
# Languages to analyze. "auto" detects from file extensions.
# languages = "auto"
# Files/directories to exclude (additive to .gitignore).
# exclude = ["**/vendor/**", "**/node_modules/**", "**/__pycache__/**", "**/dist/**", "**/build/**", "**/.git/**"]
# Random seed for reproducible Leiden partitioning on cold start.
# random_seed = 42

[snapshots]
# Where to store snapshot files (relative to repo root).
# dir = ".sdi/snapshots"
# Max snapshots to retain (oldest pruned on new capture). 0 = unlimited.
# retention = 100

[boundaries]
# Path to boundary specification file.
# spec_file = ".sdi/boundaries.yaml"
# Leiden resolution parameter (higher = more, smaller clusters).
# leiden_gamma = 1.0
# Consecutive runs a node must appear in new cluster before boundary updates.
# stability_threshold = 3
# Use weighted edges (import frequency) vs unweighted.
# weighted_edges = false

[patterns]
# Pattern categories to detect. "auto" uses built-in catalog for detected languages.
# categories = "auto"
# Minimum AST subtree size to consider as a pattern instance (nodes).
# min_pattern_nodes = 5

[thresholds]
# Max acceptable delta per snapshot interval for each dimension.
# pattern_entropy_rate = 2.0
# convention_drift_rate = 3.0
# coupling_delta_rate = 0.15
# boundary_violation_rate = 2.0

[change_coupling]
# Minimum co-change frequency (0.0-1.0) to flag cross-boundary coupling.
# min_frequency = 0.6
# Number of recent commits to analyze for co-change.
# history_depth = 500

[output]
# Default output format: "text", "json", or "csv".
# format = "text"
# Color mode: "auto" (detect TTY), "always", or "never".
# color = "auto"
"""


def _find_git_root(start: Path) -> Path | None:
    """Walk up from start to find the nearest directory containing .git."""
    current = start.resolve()
    while True:
        if (current / ".git").exists():
            return current
        parent = current.parent
        if parent == current:
            return None
        current = parent


def _update_gitignore(gitignore_path: Path) -> None:
    """Add .sdi/cache/ to .gitignore if not already present."""
    entry = ".sdi/cache/"
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")
        if entry in existing:
            return
        updated = (
            existing.rstrip("\n")
            + "\n\n# SDI cache (auto-generated, do not commit)\n"
            + entry
            + "\n"
        )
    else:
        updated = "# SDI cache (auto-generated, do not commit)\n" + entry + "\n"
    write_atomic(gitignore_path, updated)


_BOUNDARIES_TEMPLATE = """\
sdi_boundaries:
  version: "0.1.0"
  generated_from: "manual"
  modules: []
  allowed_cross_domain: []
  aspirational_splits: []
"""


@click.command("init")
@click.option("--force", is_flag=True, help="Overwrite existing .sdi/config.toml.")
@click.option(
    "--propose-boundaries",
    "propose_boundaries",
    is_flag=True,
    help="Write a starter boundaries.yaml (from latest snapshot if available).",
)
@click.pass_context
def init_cmd(ctx: click.Context, force: bool, propose_boundaries: bool) -> None:
    """Initialize SDI in the current git repository.

    Creates .sdi/config.toml with commented defaults, .sdi/snapshots/,
    and adds .sdi/cache/ to .gitignore.
    """
    cwd = Path.cwd()
    git_root = _find_git_root(cwd)
    if git_root is None:
        click.echo(
            "[error] Not inside a git repository. Run sdi init from within a git repo.",
            err=True,
        )
        sys.exit(2)

    sdi_dir = git_root / ".sdi"
    config_path = sdi_dir / "config.toml"
    snapshots_dir = sdi_dir / "snapshots"

    already_initialized = config_path.exists()
    if already_initialized and not force:
        click.echo(f"SDI already initialized at {sdi_dir}. Use --force to reinitialize.")
        if propose_boundaries:
            _write_starter_boundaries(sdi_dir, force=force)
        return

    sdi_dir.mkdir(exist_ok=True)
    snapshots_dir.mkdir(exist_ok=True)
    write_atomic(config_path, _CONFIG_TEMPLATE)
    _update_gitignore(git_root / ".gitignore")

    action = "Reinitialized" if already_initialized else "Initialized"
    click.echo(f"{action} SDI at {sdi_dir}")

    if propose_boundaries:
        _write_starter_boundaries(sdi_dir, force=force)


def _write_starter_boundaries(sdi_dir: Path, force: bool = False) -> None:
    """Write a starter boundaries.yaml, inferred from the latest snapshot if one exists."""
    boundaries_path = sdi_dir / "boundaries.yaml"
    if boundaries_path.exists() and not force:
        click.echo(f"  boundaries.yaml already exists at {boundaries_path}. Use --force to overwrite.")
        return

    content = _infer_boundaries_from_snapshot(sdi_dir) or _BOUNDARIES_TEMPLATE
    write_atomic(boundaries_path, content)
    click.echo(f"  Wrote starter boundaries.yaml at {boundaries_path}")


def _infer_boundaries_from_snapshot(sdi_dir: Path) -> str | None:
    """Try to infer boundaries from the latest snapshot's partition data."""
    snapshots_dir = sdi_dir / "snapshots"
    if not snapshots_dir.exists():
        return None
    try:
        from sdi.snapshot.storage import list_snapshots, read_snapshot
        from sdi.cli.boundaries_cmd import _partition_to_proposed_yaml

        paths = list_snapshots(snapshots_dir)
        if not paths:
            return None
        snap = read_snapshot(paths[-1])
        pd = snap.partition_data
        if not pd or not pd.get("vertex_names"):
            return None
        return _partition_to_proposed_yaml(pd)
    except Exception:
        return None
